name: 'PostgreSQL Backup to GitHub'
description: 'Take periodic backups of PostgreSQL databases and push them into a GitHub repository.'
author: 'optim4tech-devops-team'

inputs:
  backup_frequency:
    description: >
      Defines how often the backup should be taken. 
      Accepted values:
      - `daily`: triggers daily backup
      - `weekly`: triggers weekly backup
      - `monthly`: triggers monthly backup
      
      Affects the folder structure and commit message.
    required: true

  github_token:
    description: 'GitHub token with push access to target repository'
    required: true

  db_list_file:
    description: 'Path to the file containing comma-separated PostgreSQL database names'
    required: true
    default: './project.txt'

  target_repo:
    description: 'The GitHub repository to push backups to (e.g., user/repo)'
    required: true

  target_branch:
    description: 'Target branch of the repository to push backups into'
    required: true
    default: 'main'

  pg_user:
    description: 'PostgreSQL username'
    required: true

  pg_password:
    description: 'PostgreSQL password'
    required: true

  pg_host:
    description: 'PostgreSQL host'
    required: true

  pg_port:
    description: 'PostgreSQL port'
    required: true

  git_user_name:
    description: 'Git username for commit messages'
    required: false
    default: 'postgres-backup-action'

  git_user_email:
    description: 'Git email for commit messages'
    required: false
    default: 'noreply@github.com'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client gzip git

    - name: Run PostgreSQL Backup Script
      shell: bash
      run: ./entrypoint.sh
      env:
        FREQ: ${{ inputs.backup_frequency }}
        GITHUBTOKEN: ${{ inputs.github_token }}
        DB_LIST_FILE: ${{ inputs.db_list_file }}
        TARGET_REPO: ${{ inputs.target_repo }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
        PG_USER: ${{ inputs.pg_user }}
        PG_PASSWORD: ${{ inputs.pg_password }}
        PG_HOST: ${{ inputs.pg_host }}
        PG_PORT: ${{ inputs.pg_port }}
        GIT_USER_NAME: ${{ inputs.git_user_name }}
        GIT_USER_EMAIL: ${{ inputs.git_user_email }}
